### PR TITLE
Check in toy example notebook

### PR DESCRIPTION
**Pull request by maxentile**
- Illustrates perturbed quartic system
- Estimates the RMSE and bias of free energy estimate with / without
shadow work, where initial conditions are distributed according to
integrator's N.E.S.S.

### CODE REVIEW

**Comment by jchodera** [comment]
This is awesome!

Regarding the work distributions: 
work-distributions
I believe it's common to plot `Pforward(w)` and `Preverse(-w)` since the overlap in these two distributions determines how precisely the free energy difference can be estimated. The free energy difference is at the intersection. If the distributions overlap too much, it may be that the two states have too high of an overlap here.

**Comment by jchodera** [comment]
David Sivak likely had to play around with particular conditions for the overlap or switching rates in order to get measurable biases due to shadow work omission in [this paper](http://threeplusone.com/Sivak2013a.pdf): 
image

**Comment by maxentile** [comment]
Thanks, John!

Re: plotting p_forward(w) and p_reverse(-w) -- all on the same axes ends up looking a bit cluttered: 
image

can split into two separate plots:
image
image

Preference?

Re: playing with switching rates / perturbation magnitude -- I'll sweep over a few conditions momentarily...

**Comment by maxentile** [comment]
As you'd expect, the shadow work contribution is relatively less important in the limit of fast switching.

image
image


image
image


image
image


image
image


image
image


image
image

**Comment by jchodera** [comment]
Awesome!

My guess is that the initial distributions overlap so well that it is difficult to see much of an effect here. When the initial distributions overlap very poorly, longer switching times are critical to (in principle) reach good overlap. As we add in more degrees of freedom (perhaps additional degrees of freedom that are purely harmonic or quartic?), the contribution of the shadow work per timestep grows, so we would expect to see a larger error as the switching time grows if shadow work is omitted---UNLESS the shadow work contribution these additional degrees of freedom is conditionally independent, which is will be by construction. There may be a model where we can control the degree of coupling, such as in your coupled power oscillators.

**Comment by jchodera** [comment]
@maxentile : The new figures are great! Thanks for checking them in!

**Comment by maxentile** [comment]
Thanks! I think the system illustration figure is pretty much done, but I haven't settled on a good way to illustrate how the error depends on protocol length, so each protocol length gets its own plot for now...

>My guess is that the initial distributions overlap so well that it is difficult to see much of an effect here. When the initial distributions overlap very poorly, longer switching times are critical to (in principle) reach good overlap. As we add in more degrees of freedom (perhaps additional degrees of freedom that are purely harmonic or quartic?), the contribution of the shadow work per timestep grows, so we would expect to see a larger error as the switching time grows if shadow work is omitted---UNLESS the shadow work contribution these additional degrees of freedom is conditionally independent, which is will be by construction. There may be a model where we can control the degree of coupling, such as in your coupled power oscillators.

The system as-is seems to exhibit considerably biased free energy estimates at all protocol lengths tested when shadow work is neglected, although it's not really visible in the work distribution histograms. I agree that the coupled power oscillators would be a helpful model system to inspect soon.

**Comment by jchodera** [comment]
> Thanks! I think the system illustration figure is pretty much done, but I haven't settled on a good way to illustrate how the error depends on protocol length, so each protocol length gets its own plot for now...

It would be great to open this up so Gavin can see it and give feedback/insight. I don't think there's any risk in making it public---do you?

For figures [showing the error vs number of samples](https://github.com/choderalab/importance-of-shadow-work/blob/12a286ac9ec4b3409f612d07d41595889b541910/notebooks/bias_10.jpg), I tend to favor 
* A 3 rows x 1 column, full-page width figure in which the rows are bias, stddev, and RMSE
* Showing the x-axis (# protocol samples) on a log scale
* Possibly also showing the y-axis on a log scale if this would show "with shadow work" continuing to decrease
* Showing the actual data points at which we have estimates as circles, and maybe ditching the lines connecting sequential points (or making them thin)
* Moving the legend somewhere there are few features, like the upper-right

**Comment by maxentile** [comment]
Thanks! All of the proposed changes sound good to me -- will take a stab at it in the morning.

>It would be great to open this up so Gavin can see it and give feedback/insight. I don't think there's any risk in making it public---do you?

Good point! I had initialized it as a private repository, but don't have any good reason to keep it private. I'll open it up momentarily...

**Comment by jchodera** [comment]
> The system as-is seems to exhibit considerably biased free energy estimates at all protocol lengths tested when shadow work is neglected, although it's not really visible in the work distribution histograms.

Interesting! Could you also generate a plot resembling Fig 5 from [this Roux paper](http://pubs.acs.org/doi/pdf/10.1021/acs.jctc.5b00261)?

**Comment by jchodera** [comment]
Also, I realize the figures should actually be showing all of the following 8 combinations
* initially in $\pi$ or $\rho$
* including or omitting shadow work
* measuring error to $\pi$-derived free energy or to $\rho$-derived free energy

In particular, I think Roux's claim is that the error introduced by finite timesteps means that the CFT still works for the $\rho$-derived free energies if we are initially in $\rho$ and omit shadow work. So that's the most critical combination to check.

**Comment by maxentile** [comment]
>In particular, I think Roux's claim is that the error introduced by finite timesteps means that the CFT still works for the $\rho$-derived free energies if we are initially in $\rho$ and omit shadow work. So that's the most critical combination to check.

Ahh, great point -- I hadn't thought to use both as "ground-truth's" here...

To check which estimates might converge to which free energy differences, I computed the $\rho$-derived free energy difference to high precision using numerical quadrature, plotted the ground-truth $\pi$- vs. $\rho$-derived free energy differences as grey lines, and 100 replicates each of the various nonequilibrium estimates in color:

image

image

image

image

image


Anecdotally, it looks like:
* Neglecting shadow work during switching yields an estimate that doesn't appear to converge exactly to either the $\rho$-derived or $\pi$-derived free energy difference in this system, at the protocol lengths examined so far.
* If you include shadow work during switching but use initial conditions distributed according to $\rho_0, \rho_1$, you appear to estimate the $\rho$-derived free energy difference in the limit of slow switching. I'll want to double-check this by looking at even-slower switching protocols in this system, and then a few other systems...
* Although biased, the estimate that ignores shadow work has dramatically lower variance under slow switching. (We know that in the limit of infinitely slow switching, the variance of the protocol work will go to zero, but the variance of the shadow work will be >0, so it will be important to check what the behavior looks like for realistic protocol-length ranges for realistic molecular systems.)

Will attempt to understand and replicate Figure 5 next...

**Comment by jchodera** [comment]
> To check which estimates might converge to which free energy differences, I computed the $\rho$-derived free energy difference to high precision using numerical quadrature, plotted the ground-truth $\pi$- vs. $\rho$-derived free energy differences as grey lines, and 100 replicates each of the various nonequilibrium estimates in color:

These plots are awesome---thanks!

I'm really surprised that the green line in 1000 switching steps (starting in $\rho$ but then using protocol+shadow work for NCMC) manages to converge to the $\rho$-derived free energy difference (dashed line) in the limit of many samples, but that this does not happen for short switching times. That one will require some thought.

**Comment by maxentile** [comment]
>I'm really surprised that the green line in 1000 switching steps (starting in $\rho$ but then using protocol+shadow work for NCMC) manages to converge to the $\rho$-derived free energy difference (dashed line) in the limit of many samples, but that this does not happen for short switching times. That one will require some thought.

It could be that there's not really a pattern here, and that this will go away when we look at even-longer switching times. Will check a few more conditions later today...

**Comment by jchodera** [comment]
Important question: What integrator was being used for the rho equilibrium and nonequilibrium switching simulations? A big outstanding question for us is what happens if we use OVRRVO (VVVR) vs VROORV (BAOAB).

**Comment by maxentile** [comment]
These results are all with OVRRVO so far -- integrator comparison will be up shortly...

**Comment by jchodera** [comment]
Merging this so it's easier to play with the notebooks!

**Pull request merged**
